AllCops:
  NewCops: enable

Layout/LineLength:
  Enabled: true
  Max: 125
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'netomox.gemspec'

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'netomox.gemspec'

Style/BlockComments:
  Enabled: true
  Exclude:
    - 'spec/spec_helper.rb'

Style/OptionalBooleanParameter:
  Enabled: false # TODO: fix boolean method parameter styles.
