@startuml
class Networks {
  +initialize()
  +network()
  +topo_data()
  networks
}
Networks --|> DSLObjectBase
Networks --- Network
class L2VlanIdName {
  +initialize()
  +topo_data()
  id
  name
}
class L2TPAttribute {
  +initialize()
  +empty?()
  +topo_data()
  descr
  eth_encap
  mac_addr
  max_frame_size
  port_vlan_id
  tp_state
  type
  vlan_id_names
}
L2TPAttribute --- L2VlanIdName
class L3TPAttribute {
  +initialize()
  +empty?()
  +topo_data()
  ip_addrs
  type
}
class L3LinkAttribute {
  +initialize()
  +topo_data()
  +empty?()
  flags
  metric1
  metric2
  name
  type
}
class L2LinkAttribute {
  +initialize()
  +topo_data()
  +empty?()
  delay
  flags
  name
  rate
  srlg
  type
}
class SupportNode {
  +initialize()
  +topo_data()
  node_ref
  nw_ref
}
class Node {
  +initialize()
  +term_point()
  +support()
  +attribute()
  +topo_data()
  attribute
  name
  supports
  term_points
  type
}
Node --|> DSLObjectBase
Node --- L2NodeAttribute
Node --- L3NodeAttribute
Node --- SupportNode
Node --- TermPoint
class NetworkAttributeBase {
  +initialize()
  +topo_data()
  +empty?()
  flags
  name
  type
}
class L3NWAttribute {
  +initialize()
  type
}
L3NWAttribute --|> NetworkAttributeBase
class L2NWAttribute {
  +initialize()
  type
}
L2NWAttribute --|> NetworkAttributeBase
class DSLObjectBase {
  +register()
}
class SupportLink {
  +initialize()
  +topo_data()
  link_ref
  nw_ref
}
class TermPointRef {
  +initialize()
  +topo_data()
  direction
  node_ref
  tp_ref
}
class SrcTPRef {
  +initialize()
}
SrcTPRef --|> TermPointRef
class DstTPRef {
  +initialize()
}
DstTPRef --|> TermPointRef
class Link {
  +initialize()
  +support()
  +attribute()
  +topo_data()
  attribute
  destination
  name
  source
  supports
  type
}
Link --|> DSLObjectBase
Link --- DstTPRef
Link --- L2LinkAttribute
Link --- L3LinkAttribute
Link --- SrcTPRef
Link --- SupportLink
class SupportTermPoint {
  +initialize()
  +topo_data()
  node_ref
  nw_ref
  tp_ref
}
class TermPoint {
  +initialize()
  +support()
  +attribute()
  +topo_data()
  attribute
  name
  supports
  type
}
TermPoint --|> DSLObjectBase
TermPoint --- L2TPAttribute
TermPoint --- L3TPAttribute
TermPoint --- SupportTermPoint
class SupportNetwork {
  +initialize()
  +topo_data()
  nw_ref
}
class Network {
  +initialize()
  +type()
  +support()
  +attribute()
  +node()
  +bdlink()
  +topo_data()
  attribute
  links
  name
  nodes
  supports
  type
}
Network --|> DSLObjectBase
Network --- L2NWAttribute
Network --- L3NWAttribute
Network --- Link
Network --- Node
Network --- SupportNetwork
class L3Prefix {
  +initialize()
  +topo_data()
  flag
  metric
  prefix
}
class L3NodeAttribute {
  +initialize()
  +topo_data()
  +empty?()
  flags
  name
  prefixes
  router_id
  type
}
L3NodeAttribute --- L3Prefix
class L2NodeAttribute {
  +initialize()
  +topo_data()
  +empty?()
  descr
  flags
  mgmt_addrs
  mgmt_vid
  name
  sys_mac_addr
  type
}
@enduml
